### ISSUE TITLE
Implement data preparation

### ISSUE THREAD

**Issue by sorenmulli** [sorenmulli/alpha_cellari_imageseg#2]
prepare_data.py to be build such that it supports:

Cutting raw image/GT into a suitable number of images. 	
Dividing images into train/eval and test.				
Saving images in efficient format (.npz or comparable pickling format).
Performing pre-processing if necessary

**Comment by Poelsemand** [comment]
Opdel vha. et shufflearray/-matrix samt unshuffling-algoritme, så det er muligt at se, hvor på marken testdata er.

**Comment by sorenmulli** [comment]
Mulige problemer:
Kommer vi også til at dividere i voids?
Det skal vi lige undgå

**Comment by Poelsemand** [comment]
Mener du regne med i standardisering? For det gør den ikke i min kode

-------- Originalbesked --------
Til 23. okt. 2019 12.00, sorenmulli skrev:
