### ISSUE TITLE
Implementer Data Augmentation

### ISSUE THREAD

**Issue by sorenmulli** [sorenmulli/alpha_cellari_imageseg#4]
Skal implementere random cropping, mirroring, flipping og andre af den slags augmentationer
Udfordringer:
1. Skal køre hurtigt, så den skal bruge Pytorches funktioner, der virker med CUDA
2. Skal virke sammen med dataloader (burde ikke være så svært)

**Comment by oskarwiese** [comment]
Nice, har vi andre issues?
